# Generated by Django 4.1.7 on 2023-03-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category_image', models.ImageField(upload_to='cat-photo')),
            ],
        ),
        migrations.CreateModel(
            name='food_login',
            fields=[
                ('user', models.EmailField(default=1, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('type', models.BooleanField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='fitem-photo')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(null=True, upload_to='item-photo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('product_image', models.ImageField(upload_to='media')),
                ('selling_price', models.PositiveIntegerField(null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amuzeapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='foodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category_image', models.ImageField(upload_to='f-photo')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amuzeapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='food_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeapp.food_login')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amuzeapp.item'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField(default=0)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'home_account',
            },
        ),
    ]
