# Generated by Django 4.1.7 on 2023-03-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='items',
        ),
    ]
