# Generated by Django 4.1.7 on 2023-03-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0003_remove_foodcategory_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='offer_discount_applied',
        ),
    ]
