# Generated by Django 4.1.1 on 2023-03-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0004_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='category_image',
            field=models.ImageField(upload_to='media/f-photo'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amuzeapp.fooditem'),
        ),
    ]
