# Generated by Django 4.1.7 on 2023-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0004_remove_book_offer_discount_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='food',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
