# Generated by Django 4.1.7 on 2023-03-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0007_book'),
        ('amuzeapp', '0007_booking'),
    ]

    operations = [
    ]
