# Generated by Django 4.1.7 on 2023-03-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0009_rename_order_id_payments_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='razorpay_payment_id',
        ),
    ]
