# Generated by Django 4.1.7 on 2023-03-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0010_remove_adultpackage_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultpackage',
            name='description',
        ),
    ]
