# Generated by Django 4.1.7 on 2023-03-31 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0011_remove_adultpackage_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
