# Generated by Django 4.1.7 on 2023-03-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0012_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_registration',
            name='license',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
