# Generated by Django 4.1.7 on 2023-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0013_food_registration_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
