# Generated by Django 4.1.7 on 2023-03-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0013_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
