# Generated by Django 4.1.7 on 2023-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0014_payments_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed_booking',
            name='count_adult',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='placed_booking',
            name='count_child',
            field=models.BigIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='placed_booking',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
