# Generated by Django 4.1.7 on 2023-03-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0015_placed_booking_count_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed_booking',
            name='payment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='amuzeapp.payments'),
        ),
    ]
