# Generated by Django 4.1.7 on 2023-04-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed_booking',
            name='food',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
