# Generated by Django 4.1.7 on 2023-03-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0016_alter_placed_booking_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed_booking',
            name='payment',
        ),
        migrations.AddField(
            model_name='placed_booking',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
