# Generated by Django 4.1.7 on 2023-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0017_alter_review_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='count_child',
            field=models.BigIntegerField(default=1, null=True),
        ),
    ]
