# Generated by Django 4.1.7 on 2023-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0017_remove_placed_booking_payment_placed_booking_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='season',
            field=models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=20, null=True),
        ),
    ]
