# Generated by Django 4.1.7 on 2023-04-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0019_bookinglimit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='fooditem',
        ),
    ]
