# Generated by Django 4.1.7 on 2023-03-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0019_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_offers',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
