# Generated by Django 4.1.7 on 2023-03-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0020_book_discount_price_book_number_of_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='package_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
    ]
