# Generated by Django 4.1.7 on 2023-04-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0021_alter_bookingfoodoption_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfoodoption',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amuzeapp.book'),
        ),
    ]
