# Generated by Django 4.1.7 on 2023-03-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0022_remove_offer_end_date_remove_offer_package_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='applied_offers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
