# Generated by Django 4.1.7 on 2023-03-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeapp', '0023_book_applied_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_offers',
        ),
    ]
